import { DetailProps } from "../RuleProps";

export const dummyDetails: DetailProps[] = [
  {
    id: 1,
    title: "[총학생회] 회칙 및 세칙1", 
    createdAt: "2022-05-16",
    fileName: "",
    fileCapacity: "",
    fileUrl: "",
  },
  {
    id: 2,
    title: "[총학생회] 회칙 및 세칙2", 
    createdAt: "2022-05-16",
    fileName: "",
    fileCapacity: "",
    fileUrl: "",
  },
  {
    id: 3,
    title: "[총학생회] 회칙 및 세칙3", 
    createdAt: "2022-05-16",
    fileName: "",
    fileCapacity: "",
    fileUrl: "",
  },
  {
    id: 4,
    title: "[총학생회] 회칙 및 세칙4",
    createdAt: "2022-05-16",
    fileName: "",
    fileCapacity: "",
    fileUrl: "",
  },
  {
    id: 5,
    title: "[총학생회] 회칙 및 세칙5",
    createdAt: "2022-05-16",
    fileName: "",
    fileCapacity: "",
    fileUrl: "",
  },
  {
    id: 6,
    title: "[총학생회] 회칙 및 세칙6",
    createdAt: "2022-05-16",
    fileName: "",
    fileCapacity: "",
    fileUrl: "",
  },
  {
    id: 7,
    title: "[총학생회] 회칙 및 세칙7",
    createdAt: "2022-05-16",
    fileName: "",
    fileCapacity: "",
    fileUrl: "",
  },
  {
    id: 8,
    title: "[총학생회] 회칙 및 세칙8",
    createdAt: "2022-05-16",
    fileName: "",
    fileCapacity: "",
    fileUrl: "",
  },
];